# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='img',
            field=models.CharField(default='https://pickaface.net/assets/images/slides/slide1.png', max_length=2000),
        ),
    ]
