# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activation', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='img',
            new_name='order_image',
        ),
    ]
